# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language: objective-c

env:
    global:
        - TARGET_ARCH="x64"
        - CONDA_INSTALL_LOCN="${HOME}/conda"
        # Defines BINSTAR_TOKEN for astropy binstar channel
        - secure: "c/MXanxumEXl7l3vXv4Bx5cCm9RBvz4bBDrAbzSf9SjqS5Xq5Fv0jbetExNKzgjKzGQ3rv8HYhpOeVabNxHEmqqI8rOl79J/L1ba0XClTIBbkeO/rM2HS0LuS95FSvx4+eeAm6m+5xVBAJW3EXVssRt56T3y69JJD0+2pEtbUCT7I88fnb1llWRcnJsZh5sB8qppklYIc1qxofcw8EiCIBwY1wHGwQ/Jq4n6VutAjEnIUaK6cX7XuO8mvyhYEcg2gww4qcSiMkb/8KcXl9t8fSshLC1tNTwLhmA4dUo0Dbgow0xtUNqzy3L/TEWhfj9hBhGijexhMSrLwMTAEgIxPNiAsrHv3EOgX2sd/UXQo+vZ96V35apfRzJrojtGQhgIEUc36tCNfH3GcnX7jWZfaPySqohZAsj/RFrFPVkhW64VcdCAyhHc3UBTy3odmiiMYkln+cXJ/G3+CENDNeR/5uwKYQ1Ez79J1KrBIXrRYBsEAR6VCbRZ/mu/ea7cSzLeo9lIu4uyiLhLLvCua4U0/YkTJFebdpR+YNDyNVNuYVXU3XQCHRhi5DbSiNWDL1O0IxKDaTdir4dIx3+UOJCdkdJbIYH17k52u9of/52KYxssVeFMj62QjYgGiFwdTSjX7hClL3LfcF63HcJNoEu0hvtavF3qMyeduoQixrRX/Ks="

    matrix:
        - CONDA_PY=27
          CONDA_NPY=19
        - CONDA_PY=34
          CONDA_NPY=19

install:
    # Install miniconda, always the version specified by CONDA_PY, because
    # bdist_conda does not properly build python 3 packages in a python 2
    # base installation. See https://github.com/conda/conda-build/issues/132
    - python ./Obvious-CI/bootstrap-obvious-ci-and-miniconda.py ${CONDA_INSTALL_LOCN} ${TARGET_ARCH} ${CONDA_PY::1} --without-obvci
    - export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH
    - conda config --set always_yes true
    - conda update conda
    # Install a couple of dependencies we need for sure.
    - conda install --yes astropy conda-build binstar jinja2
    - conda config --add channels astropy
    # Install obvious-ci; run 2to3 first if the build is python 3.
    - cd Obvious-CI; if [[ ${CONDA_PY::1} == 3 ]]; then 2to3 -w .; fi; python setup.py install; cd ..

script:
    # Get ready to build.
    - python affiliate-builder/prepare_packages.py requirements.txt
    - if [[ -d recipes ]]; then obvci_conda_build_dir.py --disable-upload recipes astropy; fi
    # Build bdist_conda-based packages
    - if [[ -d bdist_conda ]]; then bash build_bdist.sh; fi

after_success:
    # Upload to binstar...this should probably be done as the bdists are built.
    - python affiliate-builder/upload_bdists.py
